baseURL = "http://pinkagain.me/"
languageCode = "en-us"
title = "pinkagain"
theme = "ananke"

[params]
  favicon = ""
  description = "I will let you know"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/VegTan.jpg"